# Generated by Django 5.1.3 on 2024-12-01 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
    ]
