# Generated by Django 5.1.3 on 2024-12-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='booked_seats',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='booked_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat_number',
        ),
        migrations.AddField(
            model_name='screening',
            name='seats',
            field=models.TextField(default='{"A1": true, "A2": true, "A3": true, "A4": true, "A5": true, "A6": true, "B1": true, "B2": true, "B3": true, "B4": true, "B5": true, "B6": true, "C1": true, "C2": true, "C3": true, "C4": true, "C5": true, "C6": true, "D1": true, "D2": true, "D3": true, "D4": true, "D5": true, "D6": true}'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_numbers',
            field=models.JSONField(default=['A1']),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=8),
            preserve_default=False,
        ),
    ]
