# Generated by Django 5.1.3 on 2024-11-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_avatar_profile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(default='images/usersPfps/defaultPfp.jpg', upload_to='images/usersPfps/'),
        ),
    ]
