# Generated by Django 5.1.2 on 2024-12-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_companies_app', '0003_employee_image_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='images/default.webp', upload_to='images/'),
        ),
    ]
