# Generated by Django 5.1.3 on 2024-11-30 14:22

from django.db import migrations

def create_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User') 
    Profile = apps.get_model('users', 'Profile')  
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile'),
    ]

    operations = [
    ]
