# Generated by Django 5.1.3 on 2024-11-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='savings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
