# Generated by Django 5.1.3 on 2024-12-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_savings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photos/default.png', upload_to='profile_photos/'),
        ),
    ]
