# Generated by Django 5.1.2 on 2024-11-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, default='images/avatars/profileAvatar.jpg', upload_to='images/avatars'),
        ),
    ]
