# Generated by Django 5.1.3 on 2024-12-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='comment_by_approver',
            field=models.TextField(blank=True, null=True),
        ),
    ]
