# Generated by Django 5.1.3 on 2024-11-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=1024)),
                ('about', models.TextField()),
                ('birthDate', models.DateField()),
                ('exhibit', models.CharField(max_length=1024)),
                ('photo', models.ImageField(default='images/default.jpg', upload_to='images/atrists/')),
            ],
        ),
    ]
