# Generated by Django 5.1.3 on 2024-11-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(default='images/usersPfps/defaultPfp.jpg', upload_to='images/atrists/'),
        ),
    ]
