# Generated by Django 5.1.3 on 2024-12-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artist_addedat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='birthDate',
        ),
        migrations.AddField(
            model_name='artist',
            name='instagram',
            field=models.URLField(default='https://www.instagram.com/'),
            preserve_default=False,
        ),
    ]
