# Generated by Django 5.1.3 on 2024-12-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="roll",
            field=models.CharField(
                choices=[("Manager", "Manager")], default="Manager", max_length=50
            ),
        ),
    ]
