# Generated by Django 5.1.3 on 2024-12-02 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0016_roll"),
        ("projects", "0004_remove_project_roll_project_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="created_by",),
        migrations.AddField(
            model_name="project",
            name="manager",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managed_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                limit_choices_to={"name": "Team Member"},
                related_name="projects",
                to="Users.roll",
            ),
        ),
    ]
