# Generated by Django 5.1.3 on 2024-12-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_remove_session_description_partner_scheduled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uid', models.CharField(max_length=1000)),
                ('room_name', models.CharField(max_length=200)),
                ('insession', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
