# Generated by Django 5.1.3 on 2024-12-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_roommember_delete_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='readstate',
            field=models.BooleanField(default=False),
        ),
    ]
