# Generated by Django 5.1.3 on 2024-12-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_message_readstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='readstate',
            field=models.BooleanField(default=True),
        ),
    ]
