# Generated by Django 5.1.3 on 2024-12-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_profile_role_profile_name_profile_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('organization', 'Organization')], default='volunteer', max_length=20),
        ),
    ]
