# Generated by Django 5.1.3 on 2024-11-30 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_volunteerprofile_education_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('Profit', 'Profit'), ('Non-Profit', 'Non-Profit')], max_length=20)),
                ('focus_industry', models.CharField(choices=[('Medical', 'Medical'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Environment', 'Environment'), ('Technology', 'Technology')], max_length=50)),
                ('description', models.TextField()),
                ('education_level_required', models.CharField(choices=[('None', 'No Education Required'), ('High School', 'High School Diploma'), ('Bachelor', 'Bachelor’s Degree'), ('Master', 'Master’s Degree'), ('PhD', 'PhD')], max_length=50)),
                ('number_of_volunteers_needed', models.PositiveIntegerField(default=1)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.ImageField(blank=True, default='opportunity_images/default_image.png', null=True, upload_to='opportunity_images/')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='accounts.organizationprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
