# Generated by Django 5.1.3 on 2024-12-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_opportunity_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='focus_industry',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Environment', 'Environment'), ('Technology', 'Technology'), ('Religious', 'Religious')], max_length=50),
        ),
    ]
