# Generated by Django 5.1.3 on 2024-12-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_opportunity_focus_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='focus_industry',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Environment', 'Environment'), ('Technology', 'Technology'), ('Religious', 'Religious'), ('Logistics', 'Logistics')], max_length=50),
        ),
    ]
