# Generated by Django 5.1.3 on 2024-11-29 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artPieces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='addedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artpiece',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
