# Generated by Django 5.1.3 on 2024-11-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artPieces', '0002_artpiece_addedat_artpiece_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='description',
            field=models.TextField(default='about this piece'),
            preserve_default=False,
        ),
    ]
