# Generated by Django 5.1.3 on 2024-11-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artPieces', '0003_artpiece_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='photo',
            field=models.ImageField(default='images/default.jpg', upload_to='images/pieces/'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
