# Generated by Django 5.1.3 on 2024-11-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_leave', '0005_alter_leaverequest_leave_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='category',
        ),
    ]
