# Generated by Django 5.1.3 on 2024-11-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_leave', '0008_leaverequest_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='sent_to_hr',
            field=models.BooleanField(default=False),
        ),
    ]
