# Generated by Django 5.1.3 on 2024-11-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_leave', '0011_leaverequest_manager_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
