# Generated by Django 5.1.3 on 2024-11-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_leave', '0012_leaverequest_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='hr_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
