# Generated by Django 5.1.3 on 2024-11-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_leave', '0017_alter_leaverequest_hr_alter_leaverequest_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('manager_approved', 'Manager Approved'), ('rejected', 'Rejected by Manager'), ('approved_by_hr', 'Approved by HR'), ('rejected_by_hr', 'Rejected by HR')], default='pending', max_length=16),
        ),
    ]
