# Generated by Django 5.1.3 on 2024-11-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_leave', '0019_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
