# Generated by Django 5.1.3 on 2024-11-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_leave', '0021_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
