# Generated by Django 5.1.3 on 2024-11-27 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_leave_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
