# Generated by Django 5.1.2 on 2024-11-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='title',
            field=models.CharField(default='Artist', max_length=255),
        ),
    ]
