# Generated by Django 5.1.2 on 2024-11-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_artist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='logo',
            field=models.ImageField(default='static/images/default.png', upload_to='images/'),
        ),
    ]
