# Generated by Django 5.1.3 on 2024-11-29 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pet_images/')),
                ('species', models.CharField(max_length=150)),
                ('breed', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.FloatField()),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('treatment', 'Under Treatment')], default='healthy', max_length=20)),
                ('adoption_status', models.CharField(choices=[('available', 'Available for Adoption'), ('adopted', 'Adopted'), ('not_available', 'Not Available for Adoption')], default='available', max_length=20)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
