# Generated by Django 5.1.2 on 2024-11-28 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('main', '0002_remove_language_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='native_languages',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='target_languages',
        ),
        migrations.AddField(
            model_name='profile',
            name='native_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='native_language', to='main.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='target_language',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='goal_language', to='main.language'),
            preserve_default=False,
        ),
    ]
