# Generated by Django 5.1.3 on 2024-11-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationprofile',
            old_name='user',
            new_name='organization_user',
        ),
        migrations.RenameField(
            model_name='volunteerprofile',
            old_name='user',
            new_name='volunteer_user',
        ),
    ]
