# Generated by Django 5.1.3 on 2024-11-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organizationprofile_industry_focus_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprofile',
            name='organization_logo',
            field=models.ImageField(blank=True, default='organization_logos/default_logo.png', null=True, upload_to='organization_logos/'),
        ),
    ]
