# Generated by Django 5.1.3 on 2024-11-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_organizationprofile_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('High School', 'High School'), ("Associate's Degree", "Associate's Degree"), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Doctorate', 'Doctorate')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_profile.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
