# Generated by Django 5.1.3 on 2024-11-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_volunteerprofile_education_level_and_more'),
        ('organizations', '0002_remove_opportunity_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='applied_opportunities',
            field=models.ManyToManyField(blank=True, related_name='applicants', to='organizations.opportunity'),
        ),
    ]
