# Generated by Django 5.1.3 on 2024-12-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_organizationprofile_industry_focus_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
