# Generated by Django 5.1.2 on 2024-11-28 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_app', '0002_remove_fund_founder_remove_fund_fund_members_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='fund_members',
            field=models.ManyToManyField(related_name='fund_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fund_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
