# Generated by Django 5.1.2 on 2024-11-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_app', '0004_alter_fund_fund_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
