# Generated by Django 5.1.2 on 2024-11-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds_app', '0006_fund_fund_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='fund_availability',
            new_name='fund_privacy',
        ),
    ]
