# Generated by Django 5.1.2 on 2024-12-02 20:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_app', '0007_rename_fund_availability_fund_fund_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='receiving_month',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fund',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
