# Generated by Django 5.1.2 on 2024-12-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_app', '0008_fund_receiving_month_fund_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
