# Generated by Django 5.1.2 on 2024-12-02 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_app', '0009_alter_fund_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 2, 20, 59, 56, 346580, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
