# Generated by Django 5.1.3 on 2024-12-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_expense_user'),
        ('groups', '0008_alter_groupexpense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('food', 'Food'), ('petrol', 'Petrol'), ('groceries', 'Groceries'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('food', 'Food'), ('petrol', 'Petrol'), ('groceries', 'Groceries'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
