# Generated by Django 5.1.3 on 2024-12-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_expense_category_alter_budget_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('food', 'Food'), ('petrol', 'Petrol'), ('groceries', 'Groceries'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('other', 'Other'), ('goal_contributions', 'Goal Contributions')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('food', 'Food'), ('petrol', 'Petrol'), ('groceries', 'Groceries'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('other', 'Other'), ('goal_contributions', 'Goal Contributions')], default='other', max_length=20),
        ),
    ]
