# Generated by Django 5.1.3 on 2024-11-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Role",),
        migrations.AlterField(
            model_name="profile",
            name="roll",
            field=models.CharField(
                choices=[
                    ("Manager", "Manager"),
                    ("Team Lead", "Team Lead"),
                    ("Team Member", "Team Member"),
                    ("Client", "Client"),
                    ("Quality Assurance", "QA"),
                    ("Product Owner", "Product Owner"),
                    ("Stakeholder", "Stakeholder"),
                ],
                max_length=50,
            ),
        ),
    ]
