# Generated by Django 5.1.3 on 2024-12-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0005_remove_profile_username_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="media/images/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="roll",
            field=models.CharField(
                choices=[("Manager", "Manager"), ("Team Member", "Team Member")],
                max_length=50,
            ),
        ),
    ]
