# Generated by Django 5.1.3 on 2024-12-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0006_alter_profile_photo_alter_profile_roll"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="roll",
            field=models.CharField(
                choices=[("Manager", "Manager"), ("Team Member", "Team Member")],
                default="Team Member",
                max_length=50,
            ),
        ),
    ]
