# Generated by Django 5.1.3 on 2024-12-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0007_alter_profile_roll"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="roll",),
    ]
