# Generated by Django 5.1.3 on 2024-12-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0010_alter_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                default="media/images/profile_image.webp", upload_to="media/images/"
            ),
        ),
    ]
