# Generated by Django 5.1.3 on 2024-12-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0011_alter_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="images/default_profile.jpg",
                null=True,
                upload_to="images/",
            ),
        ),
    ]
