# Generated by Django 5.1.3 on 2024-12-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0013_alter_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(upload_to="media/images/"),
        ),
    ]
