# Generated by Django 5.1.3 on 2024-12-02 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0015_alter_profile_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Roll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Manager", "Manager"),
                            ("Team Member", "Team Member"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="roles", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
