# Generated by Django 5.1.3 on 2024-12-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/avatar.webp', upload_to='images/avatar/'),
        ),
    ]
