# Generated by Django 5.1.3 on 2024-12-02 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_profile_skills_delete_skill_profile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
    ]
