# Generated by Django 5.1.2 on 2024-11-28 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_artist_logo'),
        ('services', '0002_product_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artist',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='providers.artist'),
        ),
    ]
