# Generated by Django 5.1.2 on 2024-12-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_product_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/images/default.png', upload_to='images/'),
        ),
    ]
