# Generated by Django 5.1.2 on 2024-12-02 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_artist_price_range'),
        ('services', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.artist'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/images/joinus.png', upload_to='images/'),
        ),
    ]
