# Generated by Django 5.1.2 on 2024-12-03 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsubmission',
            name='Inquiries',
        ),
    ]
