# Generated by Django 5.1.3 on 2024-11-29 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='photo',
            field=models.ImageField(upload_to='places/'),
        ),
    ]
