# Generated by Django 5.1.3 on 2024-11-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('Restaurant', 'Restaurant'), ('Entertainment', 'Entertainment'), ('Café', 'Café'), ('Museum', 'Museum'), ('Park', 'Park'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
