# Generated by Django 5.1.3 on 2024-12-01 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_volunteerprofile_applied_opportunities'),
        ('organizations', '0002_remove_opportunity_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='organizations.opportunity')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.volunteerprofile')),
            ],
            options={
                'unique_together': {('volunteer', 'opportunity')},
            },
        ),
    ]
