# Generated by Django 5.1.2 on 2024-11-29 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usermessage_content_usermessage_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='sender',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='accounts.profile'),
        ),
    ]
