# Generated by Django 5.1.2 on 2024-11-29 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usermessage_receiver_alter_usermessage_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='receiver',
            new_name='user',
        ),
    ]
