# Generated by Django 5.1.2 on 2024-12-01 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_wallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
