# Generated by Django 5.1.3 on 2024-11-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='monthly_expense_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='group',
            name='pending_invitations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='group',
            name='shared_goal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='group',
            name='shared_goal_current',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
