# Generated by Django 5.1.3 on 2024-12-01 07:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_contribution_delete_membercontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupexpense',
            name='contributed_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
