# Generated by Django 5.1.3 on 2024-12-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_groupexpense_contributed_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupexpense',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('food', 'Food'), ('petrol', 'Petrol'), ('groceries', 'Groceries'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
