# Generated by Django 5.1.3 on 2024-12-02 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_remove_group_group_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupinvitation',
            old_name='invited_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='groupinvitation',
            name='accepted',
        ),
    ]
