# Generated by Django 5.1.3 on 2024-12-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_remove_group_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='unique_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
